### ISSUE TITLE
Unable to load pretrained English parser in demo.ipynb

### ISSUE THREAD

**Issue by kohei-kaji** [stanojevic/ccgtools#2]
I attempted to run the cells in notebooks/demo.ipynb sequentially using Google Colab.
However, I encountered an issue when loading the pretrained RoBERTa parser.
I was able to use the same command without any issues before.
The error message I received is as follows:

```
RuntimeError: Error(s) in loading state_dict for Model:
Unexpected key(s) in state_dict: "embedder.model.embeddings.position_ids".
```

I would greatly appreciate it if you could fix this! Thank you!

**Comment by stanojevic** [comment]
Should be fixed now with the commit 60517c7.
